### ISSUE TITLE
Minecraft Preview Depedencies

### ISSUE THREAD

**Issue by MC874** [getggos/apps#1]
Hi!
Running Minecraft Beta / Minecraft Preview requires more depedencies beside of VCLibs, it would have been usefull if there's also 3 missing depedencies here. This repo only include Xbox Game Bar, here's the list:
- Purchase App
- Xbox Live In-Game Experience
- Feedback Hub

This depedencies enforcement were forced in Minecraft Preview 1.19.10.24, earlier version of Minecraft Preview (1.19.10.22) doesn't requires above. Some screenshot of missing depedencies :
[depedencies](https://user-images.githubusercontent.com/62210133/175231924-fc1ae5b5-8cfb-4f2e-a998-1919a8917ae0.PNG)

**Comment by getggos** [comment]
Those dependencies are all included with the Xbox app.
